#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
SOURCE_REPOSITORY="${SOURCE_REPOSITORY:-Gridness/a365}"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  SOURCE_REPOSITORY=$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null || printf '%s' "$SOURCE_REPOSITORY")
fi
SOURCE_REPOSITORY_NAME="${SOURCE_REPOSITORY#*/}"

banner "a365 v3 integrations"

stage "Register the AniList OAuth client"
say "This public client ID lets a365 open AniList login and receive the browser callback locally."
open_url "https://anilist.co/settings/developer"
step "Sign in, find Developer, and choose Create New Client."
step "Set Name to: a365"
step "Set Redirect URL exactly to: http://127.0.0.1:43815/anilist/callback"
step "Save the client, then copy its numeric Client ID. No client secret is used by the TUI."
ask ANILIST_CLIENT_ID "Paste the AniList Client ID:"
[[ "$ANILIST_CLIENT_ID" =~ ^[0-9]+$ ]] || { warn "AniList Client ID must be numeric."; exit 1; }
write_env ANILIST_CLIENT_ID "$ANILIST_CLIENT_ID"

stage "Register the release GitHub App"
say "The release workflow will mint short-lived installation tokens from this private App."
open_url "https://github.com/settings/apps/new"
step "Choose a unique name such as a365-release-<your GitHub login>."
step "Use https://github.com/Gridness/a365 as the Homepage URL. Leave callback and setup URLs blank."
step "Under Webhook, clear Active; this App receives no events."
step "Under Repository permissions set Contents, Issues, and Pull requests to Read and write. Leave every other selectable permission at No access."
step "Under Where can this GitHub App be installed?, choose Only on this account, then Create GitHub App."
step "On the App's General page, copy Client ID. It is alphanumeric; the digits-only App ID is a different value."
ask RELEASE_APP_CLIENT_ID "Paste the GitHub App Client ID:"
[[ -n "$RELEASE_APP_CLIENT_ID" ]] || { warn "GitHub App Client ID cannot be empty."; exit 1; }
[[ ! "$RELEASE_APP_CLIENT_ID" =~ ^[0-9]+$ ]] || { warn "That is the numeric App ID. Copy the alphanumeric Client ID instead."; exit 1; }
write_env RELEASE_APP_CLIENT_ID "$RELEASE_APP_CLIENT_ID"

stage "Install the App on both repositories"
say "Restrict the installation to only the source and Homebrew tap repositories."
open_url "https://github.com/settings/apps"
step "Open the App you just created, choose Install App in the left sidebar, and select Gridness."
step "Choose Only select repositories, then select $SOURCE_REPOSITORY_NAME and homebrew-oosama."
step "Review the three read/write repository permissions and choose Install."
pause "Press Enter after GitHub shows the installed App."

stage "Generate and store the private key"
say "GitHub downloads this one PEM file once. It is placed directly into the repository Actions secret and never written to .env."
open_url "https://github.com/settings/apps"
step "Open the release App, stay on General, scroll to Private keys, and choose Generate a private key."
step "Keep the downloaded .pem file private. Paste its local path below; ~ is not expanded, so use the full path."
ask RELEASE_APP_PRIVATE_KEY_PATH "Path to the downloaded .pem file:"
[[ -f "$RELEASE_APP_PRIVATE_KEY_PATH" ]] || { warn "No file exists at that path."; exit 1; }
RELEASE_APP_PRIVATE_KEY=$(<"$RELEASE_APP_PRIVATE_KEY_PATH")
[[ "$RELEASE_APP_PRIVATE_KEY" == *"BEGIN RSA PRIVATE KEY"* || "$RELEASE_APP_PRIVATE_KEY" == *"BEGIN PRIVATE KEY"* ]] || { warn "That file does not look like a PEM private key."; exit 1; }
set_secret RELEASE_APP_PRIVATE_KEY "$RELEASE_APP_PRIVATE_KEY"
unset RELEASE_APP_PRIVATE_KEY
note "After the final verification succeeds, move or delete the downloaded PEM according to your key-storage policy."

stage "Allow release bypass in repository rulesets"
say "The App needs an explicit ruleset bypass because the workflow performs the validated release merge and updates the tap."
open_url "https://github.com/$SOURCE_REPOSITORY/settings/rules"
step "Open each active branch ruleset that targets main. Under Bypass list, add the release GitHub App with Always allow, then Save changes."
open_url "https://github.com/Gridness/homebrew-oosama/settings/rules"
step "Repeat for each active branch ruleset that targets the tap's default branch. Do not weaken or remove any existing rule."
pause "Press Enter after both repositories list the App as a bypass actor."

stage "Configure and verify repository values"
say "These public variables and one secret are read by the source repository's release workflow."
set_var ANILIST_CLIENT_ID "$ANILIST_CLIENT_ID"
set_var RELEASE_APP_CLIENT_ID "$RELEASE_APP_CLIENT_ID"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  step "Verifying exact variable and secret names in $SOURCE_REPOSITORY."
  gh variable get ANILIST_CLIENT_ID --repo "$SOURCE_REPOSITORY" >/dev/null || SKIPPED+=("verify ANILIST_CLIENT_ID in $SOURCE_REPOSITORY")
  gh variable get RELEASE_APP_CLIENT_ID --repo "$SOURCE_REPOSITORY" >/dev/null || SKIPPED+=("verify RELEASE_APP_CLIENT_ID in $SOURCE_REPOSITORY")
  gh secret list --repo "$SOURCE_REPOSITORY" --json name --jq '.[].name' | grep -Fx RELEASE_APP_PRIVATE_KEY >/dev/null || SKIPPED+=("verify RELEASE_APP_PRIVATE_KEY in $SOURCE_REPOSITORY")
else
  SKIPPED+=("verify Actions values in $SOURCE_REPOSITORY after authenticating gh")
fi
note "The public release workflow is intentionally not triggered by this wizard."

stage "Verify reversible App writes"
say "This proves the exact source-PR and cross-repository tap write paths before the old PAT is removed."
say "It creates and updates one draft test PR, pushes one temporary tap branch, then closes/deletes everything and revokes both short-lived tokens."
if confirm "Run the reversible GitHub App write dry run now?"; then
  scripts/verify-release-app.sh \
    --private-key "$RELEASE_APP_PRIVATE_KEY_PATH" \
    --client-id "$RELEASE_APP_CLIENT_ID" \
    --source "$SOURCE_REPOSITORY" \
    --tap Gridness/homebrew-oosama \
    --yes
else
  SKIPPED+=("GitHub App source-PR and tap-push write dry run")
  warn "Do not remove the old release PAT until this dry run passes."
fi

finish
